CoLearnSite/courses/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from courses import views
from courses.views import searchCourse

app_name = "courses"

urlpatterns = [
    path('new/', views.CreateCourse.as_view(), name="create"),
    path('detail/<int:pk>/', views.CourseDetail.as_view(), name='detail'),
    path('all/', views.ListCourse.as_view(), name="list"),
    path('enroll/<int:pk>/', views.EnrollCourse.as_view(), name='enroll'),
    path('unenroll/<int:pk>/', views.UnenrollCourse.as_view(), name='unenroll'),
    path('search/', searchCourse, name = "search_course"),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CoLearnSite/resources/urls.py
from django.urls import path
from resources import views

app_name = "resources"

urlpatterns = [
    path('create/', views.CreateResource.as_view(), name="create"),
    path('delete/<int:pk>', views.delete_view, name='delete')
] 

CoLearnSite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as v
from courses import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name = 'register'),
    path('profile_edit/', v.profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name = 'users/password_reset.html'), name = 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'users/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'users/password_reset_complete.html'), name = 'password_reset_complete'),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('courses.urls')),
    path('resources/', include('resources.urls')),
    path('assignments/', include('assignments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CoLearnSite/resources/templates/resources/create_resource_form.html
{% extends 'resources/resource_base.html' %}
{% load crispy_forms_tags %}
{% block main_content %}
    
<div class="container">
    <h1>Resource</h1>

    
    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'resources:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Share your idea</legend>
                Room name: {{course.course_name}}
                {{ form|crispy }}
            </fieldset>
            {{ form.name.errors }}
            <input type="submit" value="Submit" class="btn btn-success btn-lg">
        </form>
    {% else %}
        <div class="jumbotron">
            <h2>You cannot create a resource</h2>
        </div>
    {% endif %}
        
</div>

{% endblock main_content %}
    

CoLearnSite/resources/templates/resources/resource_base.html
{% extends 'blog/base.html' %}

{% block title %}
    
    {% block title_name %}
        
    {% endblock title_name %}
        
{% endblock title %}
    

{% block body_content %}
    
    {% block main_content %}
    
    {% endblock main_content %}
    
{% endblock body_content %}

    

CoLearnSite/resources/templates/resources/resource_confirm_delete.html
{% extends 'resources/resource_base.html' %}

{% block main_content %}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="jumbotron">
                <h2>Are you sure you want to delete this resource?</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                    <a href="{% url 'courses:list' %}" class="btn btn-primary btn-large">Cancel</a>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You are not allowed to delete a resource.</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    