CoLearnSite/blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, searchBlog, LikeView
from . import views

urlpatterns = [
    path('', views.home, name = 'blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name = 'user-posts'),
    path('about/', views.about, name = 'blog-about'),
    path('feed/', PostListView.as_view(), name = "blog-feed"),
    path('post/<int:pk>', PostDetailView.as_view(), name = "post-detail"),
    path('q/', searchBlog, name = "search_blog"),
    path('post/new/', PostCreateView.as_view(), name = "post-create"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = "post-update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = "post-delete"),
    path('like/<int:pk>', LikeView, name = "like_post"),
    
    
] 

CoLearnSite/courses/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from courses import views
from courses.views import searchCourse

app_name = "courses"

urlpatterns = [
    path('new/', views.CreateCourse.as_view(), name="create"),
    path('detail/<int:pk>/', views.CourseDetail.as_view(), name='detail'),
    path('all/', views.ListCourse.as_view(), name="list"),
    path('enroll/<int:pk>/', views.EnrollCourse.as_view(), name='enroll'),
    path('unenroll/<int:pk>/', views.UnenrollCourse.as_view(), name='unenroll'),
    path('search/', searchCourse, name = "search_course"),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CoLearnSite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as v
from courses import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name = 'register'),
    path('profile_edit/', v.profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name = 'users/password_reset.html'), name = 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'users/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'users/password_reset_complete.html'), name = 'password_reset_complete'),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('courses.urls')),
    path('resources/', include('resources.urls')),
    path('assignments/', include('assignments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CoLearnSite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from courses.models import Course
from django.urls import reverse
from ckeditor.fields import RichTextField
from hitcount.models import HitCount
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager
from embed_video.fields import EmbedVideoField

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length = 20)

    def __str__(self):
        return self.title
        class Meta:
            verbose_name = "Category"
            verbose_name_plural = "Categories"
 
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date_posted = models.DateField(auto_now_add = True)
    post = models.ForeignKey('Post', on_delete = models.CASCADE)
    content = RichTextField()

    def __str__(self): 
        return self.user.username

class UserProfile(models.Model):
    user = models.OneToOneField(User, null = True, on_delete = models.CASCADE)
    image = models.ImageField(default = 'default.jpg', upload_to = 'profile_pics')
    bio = RichTextField()
    linkedin_url = models.CharField(max_length = 255, null = True, blank = True, )

    
    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) 
            img.save(self.image.path)    

class Post(models.Model): 
    course = models.ForeignKey(Course, related_name="post", on_delete=models.CASCADE)
    title = models.CharField(max_length = 100)
    content = RichTextField()
    date_posted = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    likes = models.ManyToManyField(User, related_name = 'blog_posts')
    tags = TaggableManager()
    hit_count_generic = GenericRelation(HitCount, object_id_field = "object_pk", related_query_name = "hit_count_generic_relation")

    def total_likes(self):
        return self.likes.count()
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs = {'pk': self.pk})

CoLearnSite/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget = forms.Textarea(attrs = {
        'class': 'md-textarea form-control',
        'placeholder': 'Type here...',
        'rows': '4',
    }))

    class Meta:
        model = Comment
        fields = ['content']

CoLearnSite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Comment, Category
from courses.models import Course
from hitcount.views import HitCountDetailView
from blog.forms import CommentForm
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

 
# Create your views here.

def LikeView(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id = request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('post-detail', args = [str(pk)]))

@login_required
def searchBlog(request):
    context = {}
    posts = Post.objects.all()
    if request.method == "GET":
        query = request.GET.get("search")
        queryset = posts.filter(Q(title__icontains = query))
        total = queryset.count()
        context.update({
            'total': total,
            'query': query,
            'posts': queryset,
        })
        return render(request, "blog/search_feed.html", context)


def home(request):
    return render(request, 'blog/home.html')

def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

@login_required 
def feed(request):
    context = []
    posts = Post.objects.all()
    categories = Category.objects.all()
    tags = Tag.objects.all()
    popular_posts = Post.objects.order_by('hit_count_generic')[:3]
    context = {
        'tags': tags,
        'popular_posts': popular_posts,
        'categories': categories,
        'posts': posts,
    }
    return render(request, 'blog/feed.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/feed.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 2

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        user = get_object_or_404(User, username = self.kwargs.get('username'))
        return Post.objects.filter(author = user).order_by('-date_posted')

class PostDetailView(HitCountDetailView):
    model = Post
    count_hit = True
    form = CommentForm()



    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()

            return redirect(reverse("post-detail", kwargs = {
                'pk': post.pk
            }))
    
    def get_context_data(self, **kwargs):
        similar_posts = self.object.tags.similar_objects()[:3]
        post_comments_count = Comment.objects.all().filter(post = self.object.id).count()
        post_comments = Comment.objects.all().filter(post = self.object.id)
        context = super().get_context_data(**kwargs)
        error = get_object_or_404(Post, id = self.kwargs['pk'])
        total_likes = error.total_likes()

        liked = False
        if error.likes.filter(id = self.request.user.id).exists():
            liked = True

        context.update({
            'form': self.form,
            'post_comments': post_comments,
            'post_comments_count': post_comments_count,
            'similar_posts': similar_posts,
            'total_likes': total_likes,
            'liked': liked,
        })
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['course', 'title', 'content', 'tags']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['course', 'title', 'content', 'tags']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object() 
        if self.request.user == post.author: 
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('courses:list')
 
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

CoLearnSite/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
        <h1>About Page</h1>
        <footer>
        This CoLearn platform is created for SWE 573 course at Bogazici University
        </footer>
{% endblock content %}

CoLearnSite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset = "utf-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1">

    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <link rel="stylesheet" type ="text/css" href="{% static 'main.css' %}"/>

    {% block title %}
    {% if title %}
        <title>CoLearn - {{ title }}</title>
    {% else %}
        <title>CoLearn</title>
    {% endif %}
    {% endblock title %}
</head>
<body> 
    <header class = "site-header">
        <nav class = "navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class = "container">
            {% if user.is_authenticated %}
            <a class = "navbar-brand mr-4" href = "#">CoLearn</a>
            {% else %}
            <a class = "navbar-brand mr-4" href = "/">CoLearn</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="#">Home</a>
                {% else%}
                <a class="nav-item nav-link" href="/">Home</a>
                {% endif %}
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'blog-feed' %}">Blog</a>
                {% endif %}
              </div>
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">@{{user.username}}</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
                <div class = "alert alert-success">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            <div class="content">
              {% block body_content %}
                  
              {% endblock body_content %}
          </div> 
            {% block content %}{% endblock %}
          </div>
          {% if user.is_authenticated %}
          <div class="col-md-4">
            <div class="content-section">
              <ul class="list-group">
                  <a class="nav-item nav-link" href="{% url 'courses:list' %}">All Rooms</a>
                  <a class="nav-item nav-link" href="{% url 'courses:create' %}">Create Room</a>
              </ul>
            </div>
            {% if user in user.course.all%}
            <div class="content-section">
              <ul class="list-group">
                <h5>My rooms:</h5>
                <hr>
                {% for user in user.course.all %}
                <div class = "col-6" >{{ user.course_name }}</div>
                {% endfor %}
              </ul>
            </div>
            {% endif %}
            {{ student.course }}
            <div class="content-section">
              <ul class="list-group">
                <h5>Enrolled rooms:</h5>
                <hr>
                {% for course in course.Enrollments %}
                <div class = "col-16" >{{ course.course_name }}</div>
                {% endfor %}
              </ul>
            </div>
            {% if user in course.students.all %}
            <div class="content-section">
              <ul class="list-group">
                <h5>Room contributors:</h5>
                <hr>
                {% for students in course.students.all %}
                <div class = "col-6" >{{ students }}</div>
                {% endfor %}
              </ul>
            {% endif %} 
            </div>
          </div>
            </div>
            {% endif %}
            <br>
            <br>
          </div>
        </div>
      </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

CoLearnSite/blog/templates/blog/feed.html
{% extends "blog/base.html" %}
{% load hitcount_tags %}
{% block content %}
<title>Blog</title>
    <div class = "col-md-16">
        <div class = "sidebar px-8">
        <form class = "input-group" action = "{% url 'search_blog' %}" method = "GET" role = "form">
            <input type = "text" name = "search" id = "" class = "form-control" placeholder = "Search Posts">
            
        </form>
        </div>
    </div>
    <br>
    <br>
    <hr>
    {% if course.user.id == student.id %}
        {% for post in posts %} 
                <article class="media content-section">
                    <img  class = "rounded-circle article-img" src = "{{ post.author.profile.image.url }}">
                    <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                        <small class="text-muted">{{ post.date_posted|date:"F d, Y"}}</small> 
                        View: {% get_hit_count for post %} <i class = "fa fa-eye" aria-hidden = "True"></i>
                        | Likes : {{ post.total_likes }} | Comments: {{ post_comments_count }}
                    </div>
                    <h2>{{ post.title }}</h2>
                    <p class="article-content">{{ post.content|safe|slice:":99"}}</p>
                    <h5><a class="mr-2" href="{% url 'post-detail' post.id %}">More</a></h5>
                    <div>
                        Room: <h5>{{ post.course }}</h5>
                    </div>
                    {% for course in courses %}
                    <a href="{% url 'courses:detail' pk=courses.pk %}" class="list-group-item list-group-item-action">
                        <h5 class="mb-1">{{course.course_name}}</h5>
                    </a>
                    {% endfor %}
                    </div>
                </article>
            {% endfor %}
        {% else %}
        <h2> You did not enroll in any course </h2>
        {% endif %}
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class = "btn btn-outline-info-mb-4" href = "?page=1">First</a>
                <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.previous_page_number}}">Previous</a>
            {% endif %} 

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class = "btn btn-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class = "btn btn-outline-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.nex_page_number}}">Next</a>
            <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %} 
        {% endif %}

{% endblock content %}

CoLearnSite/blog/templates/blog/home.html
{% load static %}
{% load hitcount_tags %}
<title>CoLearn</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>

<header class="header">
  <div class="header-text">
    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
  </div>
 
</header>
<section class="landing-section landing-main">
  <div class="landing-section-content">
    <h1 class="brand">CoLearn</h1>
    <br>
    <h2>
      <span class="brand-text">Co</span>llaborative
      <br>
      <span class="brand-text">Learn</span>ing
    </h2>
      <p class="landing-main-text">
          It is about time to enjoy studying! 
          <br>
          As part of a supportive community, you will feel again inspired and accountable to reach your goals. 
          <br>
          Together we go further!
          <br>
          <br>
          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
      </p>
  </div>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  This CoLearn platform is created for SWE 573 course at Bogazici University
</section>

CoLearnSite/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class = "content-section">
        <form method = "POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Delete the post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-danger" type = "submit">Delete</button>
                <a class = "btn btn outline-secondary" href = "{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %} 

CoLearnSite/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load hitcount_tags %}
{% load embed_video_tags %}
{% load crispy_forms_tags %}
{% block content %}
<title>Blog</title>
    <article class="media content-section">
        <img  class = "rounded-circle article-img" src = "{{ object.author.profile.image.url }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted|date:"F d, Y"}}</small> 
            View: {% get_hit_count for post %} <i class = "fa fa-eye" aria-hidden = "True"></i>
            {% if object.author == user %}
                <div>
                    <a class = "btn btn-secondary btn-sm mt-1 mb-1" href = "{% url 'post-update' object.id%}">Update</a>
                    <a class = "btn btn-danger btn-sm mt-1 mb-1" href = "{% url 'post-delete' object.id%}">Delete</a>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content|safe }}</p>
        
        {% if post.image %}
        <div class = "text-center mt-8">
            <img src = "{{ post.image.url }}" style = "max-width:400px;max-height:500px;" alt= "featured-image" class = "rounded-md">
        </div>
        {% elif post.image_url %}
        <div class = "text-center mt-8">
            <img src = "{{ post.image_url }}" style = "max-width:400px;max-height:500px;" alt= "featured-image" class = "rounded-md">
        </div>
        {% else %}
        {% endif %}
        <div class = "Tags gap-xy-2 text-center">
            {% for tag in post.tags.all %}
            <a> | {{ tag }} | </a>
            {% endfor %}
        </div>
        <br>
        <hr>
        Room: <h5>{{ post.course }}</h5>
        <hr>
        <form action = "{% url 'like_post' post.pk%}" method = "POST">
            {% csrf_token %}
            {{ total_likes }} Likes
            <br>
        {% if user.is_authenticated %}
            {% if liked %}
                <button type = "submit", name = "post_id", value = "{{ post.id }}", class = "btn btn-danger btn-sm">UnLike</button> 
            {% else %}
                <button type = "submit", name = "post_id", value = "{{ post.id }}", class = "btn btn-primary btn-sm">Like</button> 
            {% endif %}
        {% else %}
            <small> <a href = "{% url 'login' %}">Login</a>Must logged in to like.</small>
        {% endif %}
        </form>
        </div>
        <br>
        <br>
        <hr>
        <div class = "section">
            <div class = "container">
                <h2>Comments -- {{ post_comments_count }}</h2>
                <div class = "row">
                    <div class = "col-lg-12 mx-auto">
                        <div class = "media-list">
                            {% for comment in post_comments %}
                            <div>
                                <img class = "avatar-avatar-sm mr-2" src = "{{ user.profile.image.url }}" style = "max-width:50px;max-height:50px;" >
                                <div class = "media-body">
                                    <div class = "small-1">
                                        <b> {{ comment.user }} </b>
                                        <time class = "ml-4 opacity-70 small-3">{{ comment.date_posted }}</time>
                                    </div>
                                    <p>{{ comment.content|safe}}</p>
                                </div>
                            </div>
                        
                            {% endfor %}
                        </div>
                        <form method = "POST" action = "{% url 'post-detail' object.id %}">
                            {% csrf_token %}
                            <div class = "form-group">
                                {{ form|crispy }}
                                {{ form.media }}
                            </div>
                            <button class = "btn btn-primary btn-block" type = "submit">Comment</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <article>
        <div class = "row">
            {% for post in similar_posts %}
            <div class = "col-lg-4 col-md-6 col-sl-10 p-3">
                <div class = "border rounded">
                    <small class = "text-primary mt-4 p-4">{{ post.title }}</small>
                    <p class = "p-4">{{ post.content|safe|slice:":50"}}<b>[...]</b></p>
                    <a href = "{% url 'post-detail' post.id %}" class = "p-4">Read More <i class = "mdi mdi-cheveron-right"></i></a>
                    <div class = "border-top p-3 mt-3 d-flex">
                        <img src = "{{ object.author.profile.image.url }}" alt = "" style = "max-width:50px;max-height:50px;" class = "rounded-pii img-fluid mr-3">
                        <div class = "form-inline">
                            <div class = "form-group">
                                <h6>{{ post.author.username }}</h6>
                            </div>
                            <div class = "form-group ml-5">
                                <small>{{ post.date_posted|date }}</small>
                            </div>
                        </div> 
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
                        
    </article>
    
{% endblock content %}

CoLearnSite/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
Room name: {{course.course_name}}
    <div class = "content-section">
        <form method = "POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Share your idea | Post now</legend>
                {{ form|crispy }}
                {{ form.media }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type = "submit">Share</button>
            </div>
        </form>
    </div>
{% endblock content %}

CoLearnSite/blog/templates/blog/search_feed.html
{% extends "blog/base.html" %}
{% load hitcount_tags %}
{% block content %}
<title>Blog</title>
    <div class = "col-md-16">
        <div class = "sidebar px-8">
        <form class = "input-group" action = "{% url 'search_blog' %}" method = "GET" role = "form">
            <input type = "text" name = "search" id = "" class = "form-control" placeholder = "Search Posts">
            
        </form>
        </div>
    </div>
    <br>
    <br>
    <hr>
    {% for post in posts %}
        <article class="media content-section">
            <img  class = "rounded-circle article-img" src = "{{ post.author.profile.image.url }}">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"F d, Y"}}</small> 
                View: {% get_hit_count for post %} <i class = "fa fa-eye" aria-hidden = "True"></i>
                | Likes : {{ post.total_likes }} | Comments: {{ post.comments_count }}
            </div>
            <h2>{{ post.title }}</h2>
            <p class="article-content">{{ post.content|safe|slice:"99"}}</p>
            <h5><a class="mr-2" href="{% url 'post-detail' post.id %}">More</a></h5>
            Room: <h5>{{ post.course }}</h5>
            <img src = "{{ uploads.image.url }}">
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class = "btn btn-outline-info-mb-4" href = "?page=1">First</a>
            <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.previous_page_number}}">Previous</a>
        {% endif %} 

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class = "btn btn-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class = "btn btn-outline-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.nex_page_number}}">Next</a>
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %} 
    {% endif %}
{% endblock content %}