CoLearnSite/assignments/urls.py
from django.urls import path
from assignments import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'assignments'
urlpatterns = [
    path('create/', views.CreateAssignment.as_view(), name="create"),
    path('detail/<int:pk>/', views.AssignmentDetail.as_view(), name='detail'),
    path('update/<int:pk>/', views.UpdateAssignment.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteAssignment.as_view(), name="delete"),
    path('submit/', views.SubmitAssignmentView.as_view(), name="submit"),
    path('submission/detail/<int:pk>/', views.SubmitAssignmentDetail.as_view(), name="submit_detail"),
    path('submission/delete/<int:pk>/', views.delete_view, name="submit_delete"),
    path('grade/<int:pk>/', views.grade_assignment, name='grade')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoLearnSite/courses/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from courses import views
from courses.views import searchCourse

app_name = "courses"

urlpatterns = [
    path('new/', views.CreateCourse.as_view(), name="create"),
    path('detail/<int:pk>/', views.CourseDetail.as_view(), name='detail'),
    path('all/', views.ListCourse.as_view(), name="list"),
    path('enroll/<int:pk>/', views.EnrollCourse.as_view(), name='enroll'),
    path('unenroll/<int:pk>/', views.UnenrollCourse.as_view(), name='unenroll'),
    path('search/', searchCourse, name = "search_course"),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CoLearnSite/resources/urls.py
from django.urls import path
from resources import views

app_name = "resources"

urlpatterns = [
    path('create/', views.CreateResource.as_view(), name="create"),
    path('delete/<int:pk>', views.delete_view, name='delete')
] 

CoLearnSite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as v
from courses import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name = 'register'),
    path('profile_edit/', v.profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name = 'users/password_reset.html'), name = 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'users/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'users/password_reset_complete.html'), name = 'password_reset_complete'),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('courses.urls')),
    path('resources/', include('resources.urls')),
    path('assignments/', include('assignments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CoLearnSite/courses/models.py
from django.db import models
from django.urls import reverse
from users.models import User
from ckeditor.fields import RichTextField
from PIL import Image

# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=200)
    course_description = models.TextField()
    user = models.ForeignKey(User, related_name="course", on_delete=models.CASCADE)
    students = models.ManyToManyField(User, through='Enrollment', related_name="student_course")

    def courseImage(self):
        if self.course_image:
            return self.course_image.url
        return ''
        
    def __str__(self):
        return self.course_name

    def get_absolute_url(self): 
        return reverse('courses:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['course_name']

class Enrollment(models.Model):
    course = models.ForeignKey(Course, related_name="enrollments",on_delete=models.CASCADE)
    student = models.ForeignKey(User, related_name="user_courses", on_delete=models.CASCADE)

    def __str__(self):
        self.student.username
        self.course.enrollments


    class Meta:
        unique_together = ('course', 'student')

CoLearnSite/courses/views.py
from django.shortcuts import render
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.contrib import messages
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from users.models import User
from courses.models import Course, Enrollment
from blog.models import Post
from assignments.models import Assignment
from resources.models import Resource
from django.db.models import Q

# Create your views here.

@login_required
def searchCourse(request):
    context = {}
    courses = Course.objects.all()
    if  request.method == "GET":
        query = request.GET.get("search_course")
        queryset = courses.filter(Q(course_name__icontains = query))
        context.update({
            'query': query,
            'courses': queryset,
        })
        return render(request, "courses/search_course.html", context)

class CreateCourse(LoginRequiredMixin, generic.CreateView):
    fields = ('course_name', 'course_description')
    model = Course
 
    def get(self, request,*args, **kwargs): 
        self.object = None 
        context_dict = self.get_context_data() 
        context_dict.update(user = self.request.user) 
        return self.render_to_response(context_dict)
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateCourse, self).form_valid(form)
    
    
class CourseDetail(generic.DetailView):
    model = Course

    def get_context_data(self,**kwargs):
        assignments = Assignment.objects.filter(course=self.kwargs['pk'])
        resources = Resource.objects.filter(course=self.kwargs['pk'])
        posts = Post.objects.filter(course = self.kwargs['pk'])
        context = super(CourseDetail, self).get_context_data(**kwargs)
        context['assignments'] = assignments
        context['resources'] = resources
        context['posts'] = posts
        return context

class ListCourse(generic.ListView):
    model = Course
    paginate_by = 3

class EnrollCourse(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('courses:detail', kwargs={'pk':self.kwargs.get('pk')})
    
    def get(self, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs.get('pk'))

        try:
            Enrollment.objects.create(student=self.request.user, course=course)
        except:
            messages.warning(self.request, 'You are already enrolled in the course.')
        else:
            messages.success(self.request, 'You are now enrolled in the course.')
        return super().get(self.request, *args, **kwargs)

class UnenrollCourse(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('courses:detail', kwargs={'pk':self.kwargs.get('pk')})

    def get(self, *args, **kwargs):

        try:
            enrollment = Enrollment.objects.filter(
                student=self.request.user,
                course__pk=self.kwargs.get('pk')
            ).get()
        except Enrollment.DoesNotExist:
            messages.warning(self.request, 'You are not enrolled in this course.')
        else:
            enrollment.delete()
            messages.success(self.request, 'You have unenrolled from the course.')
        return super().get(self.request, *args, **kwargs)

CoLearnSite/courses/templates/courses/course_base.html
{% extends 'blog/base.html' %}
    
{% block body_content %}
    <div class="container">
        
        {% block main_content %}
      
        {% endblock main_content %}
            
    </div>
{% endblock body_content %}
    

CoLearnSite/courses/templates/courses/course_detail.html
{% extends 'courses/course_base.html' %}
{% load hitcount_tags %} 
{% block main_content %}
<h1>{{course.course_name}}</h1>
<h4>Owner: @{{course.user}}</h4>
<p>Description: {{course.course_description|safe}}</p>
<hr>

<br>
<hr>
{% if user.is_authenticated %} {%if user in course.students.all%}
<a href="{% url 'courses:unenroll' pk=course.pk %}" class="btn btn-danger btn-sm">Unenroll</a>
{% else %}
<a href="{% url 'courses:enroll' pk=course.pk %}" class="btn btn-success btn-sm">Enroll</a>
{% endif %}  
{% endif %} 

{% if course.user.id == user.id or user in course.students.all%}

    <a href="{% url 'post-create' %}" class="btn btn-sm btn-fill btn-secondary button-stretch">
      <i class="fa fa-plus-circle" aria-hidden="true"> Post message</i>
    </a>
    <a href="{% url 'assignments:create' %}" class="btn btn-sm btn-fill btn-warning button-stretch">
      <i class="fa fa-plus-circle" aria-hidden="true"> Create New Challenge</i>
    </a>
    <a href="{% url 'resources:create' %}" class="btn btn-sm btn-fill btn-info button-stretch">
      <i class="fa fa-plus-circle" aria-hidden="true"> Create New Resource</i>
    </a>

  <br>
  <hr>
  <div class = "posts">
    <h3>Posts</h3>
    <ul class="list-group">
      {% for post in posts %}
      <a href="{% url 'post-detail' post.id %}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ post.date_posted }}</h5>
        </div>
        <p class="mb-1">
          <div>
            <p class="article-content">{{ post.content|safe|slice:":90"}}<b>[...]</b></p>
            <a href="{% url 'user-posts' post.author.username %}">{{ post.author }}</small>
          </div>
        </p>
      </a>
      {% empty %}
      <h6>No posts sent yet</h6>
      {% endfor %}
      <br>
      <br>
      {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class = "btn btn-outline-info-mb-4" href = "?page=1">First</a>
            <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.previous_page_number}}">Previous</a>
        {% endif %} 

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class = "btn btn-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class = "btn btn-outline-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.nex_page_number}}">Next</a>
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %} 
    {% endif %}
    </ul>
  </div>  

  <div class="assignments">
    <h3>Challenges</h3>
    <ul class="list-group">
      {% for assignment in assignments %}
      <a href="{% url 'assignments:detail' pk=assignment.pk %}" class="list-group-item list-group-item-action">
        <div class="d-flex w-300 justify-content-between">
          <h5 class="mb-1">{{assignment.assignment_name}}</h5>
          <small>{{assignment.user}}</small>
          <br>
        </div>
        <p class="mb-1">
          {{assignment.assignment_description|safe|slice:":100"}}
        </p>
        <small>Due Date: {{assignment.due_date}} {{assignment.due_time}}</small>
      </a>
      <br>
      {% empty %}
      <h6>No challenges added yet.</h6>
      {% endfor %}
    </ul>
  </div>

  <div class="resources">
    <h3>Resources</h3>
    <ul class="list-group">
      {% for resource in resources %}
      <div  class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{resource.resource_name}}</h5>
        </div>
        <p class="mb-1">
          Submission: {{resource.resource_file.name}}
          <br>
          <br>
          <a href="{{resource.resource_file.url}}" class="btn btn-sm btn-primary" download>Download</a>
        </p>
        
        {% if user.id == course.user.id %}
          <small><a href="{% url 'resources:delete' pk=resource.pk %}" class="btn btn-sm btn-danger">Delete</a></small>
        {% endif %}
      </div>
      {% empty %}
        <h6>No resources added yet</h6>
      {% endfor %}
    </ul>
  </div>
{% endif %}
  

{% endblock main_content %}

CoLearnSite/courses/templates/courses/course_form.html
{% extends 'courses/course_base.html' %}
{% load crispy_forms_tags %}
{% block main_content %}
    <h1>Create a new room</h1>
    <form action="{% url 'courses:create' %}" method="POST">
        {% csrf_token %}
        <fieldset class = "form-group">
            {{ form|crispy }}
            {{ form.media }}
        </fieldset>
        <br>
        <input type="submit" value="Create" class="btn btn-success btn-lg">
    </form>    
{% endblock main_content %}
    

CoLearnSite/courses/templates/courses/course_list.html
{% extends 'courses/course_base.html' %} 
  
{% block main_content %}
<div class="container"> 
  <div>
    <h1>Rooms</h1>
    <br>
    <div class = "col-md-16">
      <div class = "sidebar px-8">
      <form class = "input-group" action = "{% url 'courses:search_course' %}" method = "GET" role = "form">
          <input type = "text" name = "search_course" id = "" class = "form-control" placeholder = "Search Rooms">
          
      </form>
      </div>
  </div>
  <br>
  <hr>
    {% if user.is_authenticated %}
    <a href="{% url 'courses:create' %}" class="btn btn-lg btn-success">
      <i class="fa fa-plus-circle" aria-hidden="true"> Create New Room</i>
    </a>
    {% endif %}
    <br>
    <br>
    <hr>
  </div>
    <div class="card-deck">
      {% for course_item in object_list %}
      <div>
      <div class="card" style="width: 15">
        <div class="card-body">
          <h5 class="card-title">{{course_item.course_name}}</h5>
          Owner: <h6 class="card-subtitle mb-2 text-muted">{{course_item.user}}</h6>
          Description: <p class="card-text">
            {{course_item.course_description|safe}}</p>
          </p>
          <a href="{% url 'courses:detail' pk=course_item.pk %}" class="btn btn-primary card-link">More Info</a>
          {% if user.is_authenticated %}
            {%if user in course_item.students.all%}
                <a href="{% url 'courses:unenroll' pk=course_item.pk %}" class="btn btn-danger card-link">Unenroll</a>
            {% else %}
                <a href="{% url 'courses:enroll' pk=course_item.pk %}" class="btn btn-success card-link">Enroll</a>
            {% endif %}
          {% endif %}

          <p>{{course_item.students.count}} member{{course_item.students.count|pluralize}}</p>
        </div>
      </div>
      <br>
      </div>
      {% endfor %}
    </div>
  </div>
  {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class = "btn btn-outline-info-mb-4" href = "?page=1">First</a>
            <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.previous_page_number}}">Previous</a>
        {% endif %} 

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class = "btn btn-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class = "btn btn-outline-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.nex_page_number}}">Next</a>
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %} 
    {% endif %} 
  {% endblock main_content %}
</div>

CoLearnSite/courses/templates/courses/search_course.html
{% extends 'courses/course_base.html' %} 
  
{% block main_content %}
<div class="container"> 
  <div>
    <h1>Rooms</h1>
    <div class = "col-md-16">
        <div class = "sidebar px-8">
        <form class = "input-group" action = "{% url 'courses:search_course' %}" method = "GET" role = "form">
            <input type = "text" name = "search_course" id = "" class = "form-control" placeholder = "Search Rooms">
            
        </form>
        </div>
    </div>
    <br>
    {% if user.is_authenticated %}
    <a href="{% url 'courses:create' %}" class="btn btn-lg btn-success">
      <i class="fa fa-plus-circle" aria-hidden="true"> Create New Room</i>
    </a>
    {% endif %}
    <br>
    <br>
    <hr>
  </div>
    <div class="card-deck">
      {% for course_item in object_list %}
      <div>
      <div class="card" style="width: 15">
        <div class="card-body">
          <h5 class="card-title">{{course_item.course_name}}</h5>
          Owner: <h6 class="card-subtitle mb-2 text-muted">{{course_item.user}}</h6>
          Description: <p class="card-text">
            {{course_item.course_description}}</p>
          </p>
          <a href="{% url 'courses:detail' pk=course_item.pk %}" class="btn btn-primary card-link">More Info</a>
          {% if user.is_authenticated %}
            {%if user in course_item.students.all%}
                <a href="{% url 'courses:unenroll' pk=course_item.pk %}" class="btn btn-danger card-link">Unenroll</a>
            {% else %}
                <a href="{% url 'courses:enroll' pk=course_item.pk %}" class="btn btn-success card-link">Enroll</a>
            {% endif %}
          {% endif %}

          <p>{{course_item.students.count}} member{{course_item.students.count|pluralize}}</p>
        </div>
      </div>
      <br>
      </div>
      {% endfor %}
    </div>
  </div>
  {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class = "btn btn-outline-info-mb-4" href = "?page=1">First</a>
            <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.previous_page_number}}">Previous</a>
        {% endif %} 

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class = "btn btn-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class = "btn btn-outline-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.nex_page_number}}">Next</a>
        <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %} 
    {% endif %} 
  {% endblock main_content %}
</div>