CoLearnSite/assignments/urls.py
from django.urls import path
from assignments import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'assignments'
urlpatterns = [
    path('create/', views.CreateAssignment.as_view(), name="create"),
    path('detail/<int:pk>/', views.AssignmentDetail.as_view(), name='detail'),
    path('update/<int:pk>/', views.UpdateAssignment.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteAssignment.as_view(), name="delete"),
    path('submit/', views.SubmitAssignmentView.as_view(), name="submit"),
    path('submission/detail/<int:pk>/', views.SubmitAssignmentDetail.as_view(), name="submit_detail"),
    path('submission/delete/<int:pk>/', views.delete_view, name="submit_delete"),
    path('grade/<int:pk>/', views.grade_assignment, name='grade')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoLearnSite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as v
from courses import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name = 'register'),
    path('profile_edit/', v.profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name = 'users/password_reset.html'), name = 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'users/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'users/password_reset_complete.html'), name = 'password_reset_complete'),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('courses/', include('courses.urls')),
    path('resources/', include('resources.urls')),
    path('assignments/', include('assignments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CoLearnSite/assignments/models.py
from django.db import models
from users.models import User
from courses.models import Course
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.core.validators import MaxValueValidator, MinValueValidator
import os
from django.conf import settings

# Create your models here.
class Assignment(models.Model):
    assignment_name = models.CharField(max_length=200, blank=False)
    assignment_description = RichTextField()
    start_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.assignment_name

    def get_absolute_url(self):
        return reverse('assignments:detail', kwargs={'pk': self.pk}) 

class SubmitAssignment(models.Model):
    author = models.ForeignKey(User, related_name='assignment', on_delete=models.CASCADE)
    topic = models.CharField(max_length=200, blank=False)
    description = models.TextField()
    assignment_file = models.FileField(blank=False, upload_to='assignments')
    submitted_date = models.DateTimeField(default=timezone.now)
    assignment_ques = models.ForeignKey(Assignment, related_name="question", on_delete=models.CASCADE, null=True)
    graded = models.BooleanField(default=False)
    grade = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0)
        ]
    )

    def __str__(self):
        return self.topic

    def grade_assignment(self, grade):
        self.grade = grade
        self.graded = True
        self.save()

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.assignment_file.name))
        super().delete(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('assignments:submit_detail', kwargs={'pk': self.pk})

CoLearnSite/assignments/forms.py
from django.forms import ModelForm, DateInput, TimeInput, Form, DateTimeInput
from django import forms
from django.shortcuts import get_object_or_404
from assignments.models import SubmitAssignment, Assignment
from django.utils import timezone
from courses.models import Course
from users.models import User

class GradeAssignmentForm(ModelForm):
    
    class Meta:
        model = SubmitAssignment
        fields = ['grade']

class CreateAssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ('assignment_name', 'assignment_description',
                  'due_date', 'course') 
        labels = {
            'assignment_name': 'Name of the challenge',
            'assignment_description': 'Challenge description',
            'due_date': 'Due Date (yyyy-mm-dd HH:MM)' 
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
       

class SubmitAssignmentForm(ModelForm):
    class Meta:
        model = SubmitAssignment
        fields = ('topic', 'description', 'assignment_file', 'assignment_ques', 'author')

        labels = {
            'description': 'Please state your work clear and short',
            'assignment_file': 'Your work',
            'assignment_ques': 'Please choose the related challenge'
        }
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        assignment = kwargs.pop('assignment_id')
        super().__init__(*args, **kwargs)
        self.fields['assignment_ques'].queryset = self.fields['assignment_ques'].queryset.filter(pk=assignment)
        self.fields['author'].queryset = self.fields['author'].queryset.filter(username=user.username)

CoLearnSite/assignments/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import FormMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import os
from django.conf import settings

# from django.contrib import messages
from django.views import generic
from django.shortcuts import get_object_or_404
from users.models import User
from assignments.models import Assignment, SubmitAssignment
from assignments.forms import GradeAssignmentForm, CreateAssignmentForm, SubmitAssignmentForm
from courses.models import Course

# Create your views here.    
class CreateAssignment(LoginRequiredMixin, generic.CreateView):
    form_class = CreateAssignmentForm
    template_name = 'assignments/create_assignment_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs() 
        kwargs['user'] = self.request.user
        return kwargs

class UpdateAssignment(LoginRequiredMixin, generic.UpdateView):
    model = Assignment
    form_class = CreateAssignmentForm
    template_name = 'assignments/create_assignment_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def test_func(self):
        assignment = self.get_object() 
        if self.request.user == assignment.user: 
            return True
        return False

class DeleteAssignment(LoginRequiredMixin, generic.DeleteView):
    model = Assignment
    success_url = reverse_lazy('courses:list')

class SubmitAssignmentView(LoginRequiredMixin, generic.CreateView):
    form_class = SubmitAssignmentForm
    template_name = 'assignments/submitassignment_form.html'
    select_related = ('author', 'assignment_ques')

    def get_context_data(self, **kwargs):
        assignments = Assignment.objects.filter(pk=self.request.session.get('assignment'))
        assignment_object = get_object_or_404(assignments)
        context = super(SubmitAssignmentView, self).get_context_data(**kwargs)
        context['duedate'] = assignment_object.due_date
        context['time'] = timezone.now()
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['assignment_id'] = self.request.session.get('assignment')
        kwargs['user'] = self.request.user
        return kwargs

class SubmitAssignmentDetail(LoginRequiredMixin, generic.DetailView):
    model = SubmitAssignment
    template_name = 'assignments/submitassignment_detail.html'

    def get_context_data(self, **kwargs):
        submissions = SubmitAssignment.objects.filter(pk=self.kwargs['pk'])
        submissions_object = get_object_or_404(submissions)
        context = super(SubmitAssignmentDetail, self).get_context_data(**kwargs)
        context['submissions'] = submissions_object
        return context


class AssignmentDetail(LoginRequiredMixin, generic.DetailView):
    model = Assignment

    def get_context_data(self, **kwargs):
        course_obj = Course.objects.filter(students=self.request.user.id)
        context = super(AssignmentDetail, self).get_context_data(**kwargs)
        context['course'] = course_obj
        assignment = Assignment.objects.filter(pk=self.kwargs['pk'])
        assignment_object = get_object_or_404(assignment)
        context['duedate'] = assignment_object.due_date
        context['time'] = timezone.now()
        submitassignment = SubmitAssignment.objects.filter(assignment_ques=self.kwargs['pk'])
        context['submitted'] = submitassignment
        self.request.session['assignment'] = self.kwargs['pk']
        return context


@login_required
def delete_view(request, pk):
    obj = get_object_or_404(SubmitAssignment, pk=pk)
    context = {'submission': obj}
    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect(reverse("courses:list"))
    return render(request, "assignments/submission_confirm_delete.html", context)

@login_required
def grade_assignment(request, pk):
    submission = get_object_or_404(SubmitAssignment, pk=pk)
    if request.method=="POST":
        form=GradeAssignmentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data.get('grade')
            submission.grade_assignment(data)
            return redirect('assignments:submit_detail', pk=pk)
    else:
        form = GradeAssignmentForm()
    return render(request, 'assignments/grade_form.html', {'pk':pk, 'form':form, 'submissions':submission})

CoLearnSite/assignments/templates/assignments/assignment_base.html
{% extends 'blog/base.html' %}    

{% block body_content %}
    
    {% block main_content %}
    
    {% endblock main_content %}

{% endblock body_content %}
    

    

CoLearnSite/assignments/templates/assignments/assignment_confirm_delete.html
{% extends 'assignments/assignment_base.html' %}
 

{% block main_content %}
    {% if user.is_authenticated or submission.author.id == user.id %}
        <div class="container">
            <div class="jumbotron">
                <h2>Are you sure you want to delete this challenge?</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                    <a href="{% url 'assignments:detail' pk=assignment.pk %}" class="btn btn-primary btn-large">Cancel</a>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You are not allowed to delete the challenge. -- {{assignment.assignment_name}}</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    

CoLearnSite/assignments/templates/assignments/assignment_detail.html
{% extends 'assignments/assignment_base.html' %}

{% block main_content %}
    <div class="container">
        <h1>{{assignment.assignment_name}}</h1>
        <h4>Course: {{assignment.course}}</h4>
        <h6>Start Date: {{assignment.start_date}}</h6>
        <h6>Due Date: {{assignment.due_date}}</h6>
        
        <p>Description: {{assignment.assignment_description|safe}}</p>
        <hr>
        {% if user.is_authenticated or submission.author.id == user.id %}
            <a href="{% url 'assignments:update' pk=assignment.pk %}" class="btn btn-warning btn-lg">Update</a>
            <a href="{% url 'assignments:delete' pk=assignment.pk %}" class="btn btn-danger btn-lg">Delete</a>

            <div class="submissions">
            <br>
            <h3>Submissions</h3>
            <a href="{% url 'assignments:submit' %}" class="btn btn-secondary btn-lg">Submit your work</a>
            <br>
            <br>
            {% for submissions in submitted %}
                <a href="{% url 'assignments:submit_detail' pk=submissions.pk %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{submissions.topic}}</h5>
                    <small>{{submissions.author}}</small>
                    </div>
                    <p class="mb-1">
                    {{submissions.description}}
                    </p>
                    <br>
                    <hr>
                    <small>Start Date: {{submissions.submitted_date}}</small><br>
                    <br>
                    <div class="grade">
                        {% if submissions.graded == False %}
                            {% if submission.author.id == user.id %}
                            <a href="{% url 'assignments:grade' pk=submissions.pk %}" class="btn btn-secondary btn-sm">Grade</a>
                            {% else %}
                            <p>This challenge has not been controlled yet.</p>
                            {% endif %}
                        {% else %}
                            <p>This challenge has been controlled.</p>
                            Feedback score: {{submissions.grade}}
                        {% endif %}
                    </div>
                </a>
            {% empty %}
                <h6>No submitted work so far :(</h6>
            {% endfor %}
            </div>
                

        {% else %}            
            {% if assignment.course in course %}
                {% for submissions in submitted %}
                    {% if submissions.author.id == user.id %}
                        <a href="{% url 'assignments:submit_detail' pk=submissions.pk %}" class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{submissions.topic}}</h5>
                            <small>{{submissions.author}}</small>
                            </div>
                            <p class="mb-1">
                            {{submissions.description}}
                            </p>
                            <small>Start Date: {{submissions.submitted_date}}</small><br>
                        </a>
                    {% endif %}
                {% empty %}
                    <h6>No Submissions</h6>
                {% endfor %}
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock main_content %}
    

CoLearnSite/assignments/templates/assignments/assignment_list.html
{% block main_content %}
  {% if is_paginated %}

  {% if page_obj.has_previous %}
      <a class = "btn btn-outline-info-mb-4" href = "?page=1">First</a>
      <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.previous_page_number}}">Previous</a>
  {% endif %} 

  {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
          <a class = "btn btn-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class = "btn btn-outline-info-mb-4" href = "?page={{ num }}">{{ num }}</a>
      {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.nex_page_number}}">Next</a>
  <a class = "btn btn-outline-info-mb-4" href = "?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %} 
{% endif %} 
{% endblock main_content %}

CoLearnSite/assignments/templates/assignments/create_assignment_form.html
{% extends 'assignments/assignment_base.html' %}
{% load crispy_forms_tags %}
  
{% block main_content %}

<div class="container">
  <h1>Challenges</h1>
    <form method="POST" action="{% url 'assignments:create' %}">
      {% csrf_token %} 
      <fieldset class = "form-group">
        <legend class = "border-bottom mb-4">Share your idea</legend>
        Room name: {{asignment.course}}
        <hr>
        {{ form|crispy }}
        {{ form.media }}
    </fieldset>
      <input type="submit" value="Submit" class="btn btn-success btn-lg">
    </form>
   
</div>
{% endblock main_content %}

CoLearnSite/assignments/templates/assignments/grade_form.html
{% extends 'assignments/assignment_base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
    
    {% if user.is_authenticated and submissions.assignment_ques.course.user.id == user.id %}
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <fieldset class = "form-group">
                    {{ form|crispy }}
                </fieldset>
                <div>
                    <input type="submit" value="Grade" class="btn btn-success btn-lg">
                </div>
            </form>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You cannot feedback this challenge.</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    

CoLearnSite/assignments/templates/assignments/submission_confirm_delete.html
{% extends 'assignments/assignment_base.html' %}


{% block main_content %}
    {% if user.is_authenticated or submission.author.id == user.id %}
        <div class="container">
            <div class="jumbotron">
                <h2>Are you sure you want to delete this submission?</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
                    <a href="{% url 'assignments:submit_detail' pk=submission.pk %}" class="btn btn-primary btn-large">Cancel</a>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h2>You are not allowed to delete the submission</h2>
            </div>
        </div>
    {% endif %}
        
{% endblock main_content %}
    

CoLearnSite/assignments/templates/assignments/submitassignment_detail.html
{% extends 'assignments/assignment_base.html' %}
{% load static %}
{% block main_content %}
    <div class="container">
            <h1>{{submissions.topic}}</h1>
            <h4>Submitted by: {{submissions.author}}</h4>
            <h6>Submitted On: {{submissions.submitted_date}}</h6>
            <p>Description: {{submissions.description|safe}}</p>
            <p>Submission: {{submissions.assignment_file.name|slice:"20:"}}</p>
             
            <a href="{{submissions.assignment_file.url}}" class="btn btn-lg btn-primary" download>Download</a>
            <div class="grade">

            <br>
            <br>
            <hr>
                {% if submissions.graded == False %}
                    <p>This challenge has not been graded yet.</p>
                {% else %}
                    <p>This challenge has been graded.</p>
                    <p>Feedback score: {{submissions.grade}}</p>
                {% endif %}
            </div>         
            {% if user.is_authenticated and submissions.graded == False %}
                <div>
                    <form method="POST">
                        {% csrf_token %}
                        <a href="{% url 'assignments:submit_delete' pk=submissions.pk %}" 
                        class="btn btn-danger btn-lg">Delete</a>
                    </form>
                    
                </div>
            {% else %}
                {% if submissions.assignment_ques.course.user.id == user.id %}
                    {% if submissions.graded == False %}
                        <div>
                            <a href="{% url 'assignments:grade' pk=submissions.pk %}" 
                            class="btn btn-success btn-lg">Give feedback</a>
                        </div>
                    {% endif %}
                {% endif %}

            {% endif %}
    </div>
{% endblock main_content %}
    

CoLearnSite/assignments/templates/assignments/submitassignment_form.html
{% extends 'assignments/assignment_base.html' %}
{% load crispy_forms_tags %}
{% block main_content %} 
{% if duedate < time %}
<h2>Submission is closed.</h2>
<h2>Please try to be faster for the next time :)</h2>
{% endif %}
{% if duedate >= time %}
    {% if user.is_authenticated %}            
        <div class="container">
            <h2>Submit a challenge</h2>
            <form action="{% url 'assignments:submit' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.name.errors }}
                <fieldset class = "form-group">
                    {{ form|crispy }}
                    {{ form.media }}
                </fieldset>
                    <input type="submit" value="Submit" class="btn btn-warning btn-lg">
            </form>
            <ul>
            </ul> 
        </div>
    {% endif %}
{% endif %}
{% endblock main_content %}
    